// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNKqLy7iqLhFwkkXWfzXAFX9MkwpoQ1Ik',
    appId: '1:993159233696:web:3339a1bf32656aa42f89c5',
    messagingSenderId: '993159233696',
    projectId: 'desafio-odonto',
    authDomain: 'desafio-odonto.firebaseapp.com',
    storageBucket: 'desafio-odonto.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAZuJAO8-k0fDmLCvIdCV0AqoLcipnkUg',
    appId: '1:993159233696:android:d026831a149372642f89c5',
    messagingSenderId: '993159233696',
    projectId: 'desafio-odonto',
    storageBucket: 'desafio-odonto.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxFgItZ1uumptgAM_TTMgBGzGPm7RHpk4',
    appId: '1:993159233696:ios:80a519cbacaa24222f89c5',
    messagingSenderId: '993159233696',
    projectId: 'desafio-odonto',
    storageBucket: 'desafio-odonto.appspot.com',
    iosClientId: '993159233696-bp1pp6550jai67bct49p09oq62l2vcan.apps.googleusercontent.com',
    iosBundleId: 'com.example.odonto',
  );
}
